### ISSUE TITLE
Channel closed while operation in progress [JIRA: CLIENTS-603]

### ISSUE THREAD

**Issue by robstolarz** [basho/riak-java-client#551] opened 2015-09-23 18:04 UTC
Using this piece of code:

``` java
package tests;

import java.net.UnknownHostException;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.ExecutionException;

import com.basho.riak.client.api.RiakClient;
import com.basho.riak.client.api.commands.kv.FetchValue;
import com.basho.riak.client.core.query.Location;
import com.basho.riak.client.core.query.Namespace;

public class MessingAroundWithRiak {
    public static void main(String[] args) throws ExecutionException, InterruptedException, UnknownHostException {

        List<String> dbAddresses = new LinkedList<>();
        dbAddresses.add("127.0.0.1");
        final RiakClient db = RiakClient.newClient(11098,dbAddresses);

        Location location = new Location(new Namespace("TestBucket"),"TestKey");

        FetchValue fv = new FetchValue.Builder(location).build();
        FetchValue.Response response = db.execute(fv);

        // Fetch object as String
        String value = response.getValue(String.class);
        System.out.println(value);

        db.shutdown();
    }
}
```

I am getting this error:

```
[main] INFO com.basho.riak.client.core.RiakNode - RiakNode started; 127.0.0.1:11098
[main] INFO com.basho.riak.client.core.RiakCluster - RiakCluster is starting.
[nioEventLoopGroup-2-2] ERROR com.basho.riak.client.core.RiakNode - Channel closed while operation in progress; id:-523276175 127.0.0.1:11098
[nioEventLoopGroup-2-1] ERROR com.basho.riak.client.core.RiakNode - Channel closed while operation in progress; id:-356331643 127.0.0.1:11098
[nioEventLoopGroup-2-8] ERROR com.basho.riak.client.core.RiakNode - Channel closed while operation in progress; id:1047610939 127.0.0.1:11098
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.Exception: Connection closed unexpectedly
    at com.basho.riak.client.core.FutureOperation.get(FutureOperation.java:260)
    at com.basho.riak.client.api.commands.CoreFutureAdapter.get(CoreFutureAdapter.java:52)
    at com.basho.riak.client.api.RiakCommand.execute(RiakCommand.java:89)
    at com.basho.riak.client.api.RiakClient.execute(RiakClient.java:293)
    at tests.MessingAroundWithRiak.main(MessingAroundWithRiak.java:23)
Caused by: java.lang.Exception: Connection closed unexpectedly
    at com.basho.riak.client.core.RiakNode$3.operationComplete(RiakNode.java:162)
    at com.basho.riak.client.core.RiakNode$3.operationComplete(RiakNode.java:142)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:679)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:569)
    at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:412)
    at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
    at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:856)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:550)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:66)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:143)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:494)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:461)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Thread.java:745)
```

Riak seems to be working happily on localhost, but my Java sample cannot connect to it. I cannot figure out why.

**Comment by robstolarz** [comment] 2015-09-24 19:47
Found the issue. When connecting to the HTTP port using the (protobuf only) Java client, it gives weird errors. Perhaps writing a test to make sure we're connected to a protobuf and not an http server into initialization would be sensible. Should I try something like that?

**Comment by alexmoore** [comment] 2016-02-09 22:05
Hey Rob,

Thanks for the report.  I'll put this in my notes as this happens more often than you'd think.
I'll go ahead and close the issue.

Thanks,
Alex

**Closed as completed by alexmoore** 2016-02-09 22:05 UTC
Labels: JIRA: Closed

**Comment by hugocosta88** [comment] 2017-05-17 14:55
@alexmoore 
Was this problem solved?
Is there any advice to avoid it? We are getting a lot of these errors when the number of parallel queries increases. We are using client version 2.0.7.

**Comment by alexmoore** [comment] 2017-05-17 16:15
@hugocosta88 The issue was that they were connecting to Riak's HTTP port, instead of Riak's PB port.  The client can't tell the difference between the two, so it just errors out.

**Comment by alexmoore** [comment] 2017-05-17 16:16
@hugocosta88 So there's nothing to fix, it's caused by user error in the original case.

**Comment by hugocosta88** [comment] 2017-05-17 16:21
@alexmoore 
Thank you for the explanation.
We might open a different issue for our problem with a high number of connections on port 8087. We will explore and create it with the full details.
